### ISSUE TITLE
[QA] Todo before deploy

### ISSUE THREAD

**Issue by maxogden** [datproject/datproject.org#365]
- [ ] Viewing a dat /view/#hash
- [ ] Dat Desktop download app works (has latest version)
- [ ] Open Dat In Desktop from /view page
- [ ] Example datasets all have working Dat links (that you can actually download)
- [ ] Test on mobile, test in major browsers for JS/css errors
- [ ] check all nav links work for different subviews

**Comment by clkao** [comment]
` Example datasets all have working Dat links (that you can actually download)` needs to go to integration tests, and the rest should be manully checked.

**Comment by joehand** [comment]
Some links that need to update: 

- [ ] `Page source on github` (on bottom) github link goes to old repo 
- [ ] Connect > github: point this to the org instead of datproject/dat

**Comment by karissa** [comment]
thanks @joehand !
